# Google Cloud & Drive Settings
json_key_file = "photovotingapp-476406-eb39e1d21798.json"
target_folder_id = "1eubMA-cGncDunvk1_JcRsefke-JtcDlN"
spreadsheet_name = "投票用"
vote_sheet_name = "投票"
fav_sheet_name = "お気に入り"